language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_shoes_api_db_test

node_js: "12"

before_script:
  - psql -c 'create database  my_shoes_api_db_test;' -U postgres
  - psql -U postgres -d my_shoes_api_db_test -a -f table.sql

services:
  - postgresql